defaults:
  - env: quad
  # - _self_

seeds: [12]
# seeds: [12, 13, 14, 15]

agent:
  tau: 0.005
  n_warmup_batches: 5
  update_target_every_steps: 2
  leave_print_every_n_secs: 300
  train:
    gamma: 0.99
    max_minutes: 36 #0
    max_episodes: 150 #0
    goal_mean_100_reward: 140_000

train_strategy:
  _target_: beads_gym.rl.noisy_strategies.NormalNoiseDecayStrategy
  init_noise_ratio_mult: 0.1
  min_noise_ratio_mult: 0.01
  init_noise_ratio_add: 1.5
  min_noise_ratio_add: 0.01
  decay_steps: 1_000_000

eval_strategy:
  _target_: beads_gym.rl.noisy_strategies.GreedyStrategy

# Not that easy
# policy:
#   _target_: .FCDP
#   hidden_dims: [300, 300]
