_target_: beads_gym.environment.generic_environment.GenericEnvironment

do_render: null
do_record: null
monitor_mode: null

which_beads_actuate: [0, 1, 2, 3]

env_backend:
  _target_: beads_gym.environment.environment_cpp.EnvironmentCpp
  timestep: 0.001
  num_internal_steps: 10
  theta: 0.99999
  sigma: 0.0000000001

beads:
  - _target_: beads_gym.beads.beads.Bead
    id: 0
    position: [0.5, 0.5, 0]
    mass: 1.0
    is_mobile: true
  - _target_: beads_gym.beads.beads.Bead
    _args_: [1, [-0.5, 0.5, 0], 1.0, true]
  - _target_: beads_gym.beads.beads.Bead
    _args_: [2, [-0.5, -0.5, 0], 1.0, true]
  - _target_: beads_gym.beads.beads.Bead
    _args_: [3, [0.5, -0.5, 0], 1.0, true]
  - _target_: beads_gym.beads.beads.Bead
    _args_: [4, [0, 0, -0.25], 1.0, true]
  - _target_: beads_gym.beads.beads.Bead
    _args_: [5, [0, 0, 1.25], 1.0, true]


bonds:
  - _target_: beads_gym.bonds.bonds.DistanceBond
    bead_id_1: 0
    bead_id_2: 1
    k: 3000.
  - _target_: beads_gym.bonds.bonds.DistanceBond
    _args_: [1, 2, 3000.]
  - _target_: beads_gym.bonds.bonds.DistanceBond
    _args_: [2, 3, 3000.]
  - _target_: beads_gym.bonds.bonds.DistanceBond
    _args_: [3, 0, 3000.]

  - _target_: beads_gym.bonds.bonds.DistanceBond
    _args_: [0, 2, 4000.]
  - _target_: beads_gym.bonds.bonds.DistanceBond
    _args_: [1, 3, 4000.]

  - _target_: beads_gym.bonds.bonds.DistanceBond
    _args_: [0, 4, 4000.]
  - _target_: beads_gym.bonds.bonds.DistanceBond
    _args_: [1, 4, 4000.]
  - _target_: beads_gym.bonds.bonds.DistanceBond
    _args_: [2, 4, 4000.]
  - _target_: beads_gym.bonds.bonds.DistanceBond
    _args_: [3, 4, 4000.]
  - _target_: beads_gym.bonds.bonds.DistanceBond
    _args_: [4, 5, 4000.]

bead_groups:
  - [0, 1, 2, 3]
